apiVersion: v1
kind: PersistentVolume
metadata:
 name: sonarqube-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /exports/sonarqube-data
    server: sorento.ocb.org.br
  persistentVolumeReclaimPolicy: Retain
