apiVersion: v1
kind: Template
labels:
  template: cicd
  group: cicd
metadata:
  annotations:
  name: cicd
objects:
# Pipeline
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind": "DeploymentConfig"}]'
    labels:
      app: cicd-pipeline
      name: cicd-pipeline
    name: lib-pipeline
  spec:
    triggers:
      - type: "Generic"
        generic:
          secretReference:
                name: "lib"
          allowEnv: true
    runPolicy: Serial
    source:
      type: None
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |-
             def version, mvnCmd = "mvn -s configuration/settings.xml"
             pipeline {
               agent {
                 node {
                  label 'maven'
                 }
               }
               stages {
                 stage( 'build package' ) {
                   steps {
                     git branch: 'hmlg', credentialsId: '666d9fae-0115-4085-a8c6-e4a5f12782d7', url: '@git@'
                       script {
                         def pom = readMavenPom file: 'pom.xml'
                         version = pom.version
                       }
                     sh "${mvnCmd} clean install -DskipTests=true"
                   }
                 }  
                 stage( 'Testing' ) {
                   steps {
                     sh "${mvnCmd} test"
                     step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
                   }
                 }  
                 stage('Code analysis') {
                   steps {
                    script {
                      sh "${mvnCmd} sonar:sonar -Dsonar.host.url=http://@host_sonar@:9000/sonar -DskipTests=true"
                    }
                  } 
                }
                stage('Upload nexus') {
                  steps {
                    sh "${mvnCmd} deploy -DskipTests=true -P nexus"
                  }
                }
               }
              }
        type: JenkinsPipeline
- kind: Secret
  apiVersion: v1
  metadata:
    name: lib
    creationTimestamp:
  data:
    WebHookSecretKey: YmQxZDI1YzZjZGNmZWM3ZA==
