apiVersion: v1
kind: PersistentVolume
metadata:
 name: jenkins
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /exports/jenkins-data
    server: sorento.ocb.org.br
  persistentVolumeReclaimPolicy: Retain
