apiVersion: v1
kind: PersistentVolume
metadata:
 name: maven
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /exports/maven-data
    server: master.openshift.local
  persistentVolumeReclaimPolicy: Retain
